name: flutter_login
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  formz: ^0.8.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  bloc: ^9.0.0


dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail:

flutter:
  uses-material-design: true


